permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Hugo Dantas
url: https://esponja92.github.io
description: Cientista da Computação, hater de Beatles, fanboy do programa Fantasia
twitter: esponja92
